name: Bug report
description: Create a report to help us improve
title: "[BUG] - <title>"
labels: ["type:Bug"]

body:
  - type: markdown
    attributes:
      value: |
        Hi! Thanks for using the temperature plotting and taking some time to contribute to this project.
        We'd appreciate it if you could check out the [Troubleshooting common problems](https://venustiano.github.io/temperature_plotting/) section in the documentation,
        as well as [existing issues](https://github.com/Venustiano/temperature_plotting/issues) prior to submitting an issue to avoid duplication.
        Please answer the following sections to help us troubleshoot the problem.
  - type: dropdown
    id: docker_images
    attributes:
      label: What docker image(s) are you using?
      description: Select as many images as applicable
      multiple: true
      options:
        - rvispack
        - genenettools
    validations:
      required: true
